services:
  vakilsahab-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: vakilsahab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      UV_LINK_MODE: copy
      PYTHONUNBUFFERED: 1
      HF_HUB_DISABLE_XET: 1
    restart: unless-stopped
