import {
  IconCorporate,
  IconCriminal,
  IconHome,
  IconPersonalInjury,
  IconRealEstate,
  IconTaxLaw,
} from "@/lib/icons";
import { Lawyer } from "@/types/lawyer";

export const popularCategories = [
  {
    name: "Family Law",
    services: ["Divorce", "Custody"],
    Icon: IconHome,
  },
  {
    name: "Corporate",
    services: ["Business", "Contracts"],
    Icon: IconCorporate,
  },
  {
    name: "Criminal",
    services: ["Defense", "Appeals"],
    Icon: IconCriminal,
  },
  {
    name: "Personal Injury",
    services: ["Accidents", "Malpractice"],
    Icon: IconPersonalInjury,
  },
  {
    name: "Tax Law",
    services: ["Planning", "Disputes"],
    Icon: IconTaxLaw,
  },
  {
    name: "Real Estate",
    services: ["Property", "Leasing"],
    Icon: IconRealEstate,
  },
];

export const fakeLawyersData: Lawyer[] = [
  {
    id: "1",
    firstName: "Priya",
    lastName: "Sharma",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/85",
    specialization: "Family Lawyer Specialist",
    consultationFees: 4000,
    bio: "15+ years of experience helping families navigate complex legal matters with compassion and expertise.",
    services: ["Divorce", "Child Custody", "Mediation"],
    rating: 4.9,
    reviewCount: 128,
    experienceInYears: 15,
  },
  {
    id: "2",
    firstName: "Rahul",
    lastName: "Singh",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/25",
    specialization: "Corporate Attorney",
    consultationFees: 16000,
    bio: "Specializing in helping startups and established businesses with legal strategy, contracts, and compliance.",
    services: ["Contracts", "Business Law", "Mergers"],
    rating: 4.8,
    reviewCount: 95,
    experienceInYears: 10,
  },
  {
    id: "3",
    firstName: "Anjali",
    lastName: "Gupta",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/91",
    specialization: "Criminal Defense Attorney",
    consultationFees: 6000,
    bio: "Aggressive defense attorney with a proven track record of successful case dismissals and favorable outcomes.",
    services: ["Criminal Defense", "DUI", "Appeals"],
    rating: 4.7,
    reviewCount: 83,
    experienceInYears: 8,
  },
  {
    id: "4",
    firstName: "Rohan",
    lastName: "Patel",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/18",
    specialization: "Real Estate Attorney",
    consultationFees: 5200,
    bio: "Expert in residential and commercial real estate transactions, property disputes, and landlord-tenant matters.",
    services: ["Property Law", "Leasing", "Zoning"],
    rating: 4.9,
    reviewCount: 112,
    experienceInYears: 12,
  },
  {
    id: "5",
    firstName: "Aisha",
    lastName: "Khan",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/72",
    specialization: "Immigration Attorney",
    consultationFees: 3200,
    bio: "Dedicated to helping individuals and families navigate the complex immigration system with personalized service.",
    services: ["Visas", "Green Cards", "Citizenship"],
    rating: 4.8,
    reviewCount: 76,
    experienceInYears: 7,
  },
  {
    id: "6",
    firstName: "Vikram",
    lastName: "Yadav",
    email: "kodewithkk@gmail.com",
    phoneNumber: "8303286968",
    photo: "https://avatar.iran.liara.run/public/45",
    specialization: "Personal Injury Attorney",
    consultationFees: 0,
    bio: "Fighting for maximum compensation for injury victims with a no-win, no-fee guarantee on all personal injury cases.",
    services: ["Car Accidents", "Medical Malpractice", "Workplace Injuries"],
    rating: 4.7,
    reviewCount: 92,
    experienceInYears: 9,
  },
];
